const items = [
    {
        id: 1,
        title: "Bluetooth Wireless Earbuds",
        desc: "Enjoy your favorite tunes on the go with these high-quality wireless earbuds. The earbuds come with a charging case and offer a long battery life, making them perfect for travel.",
        price: 49.99,
        stock: 50,
        img: "https://source.unsplash.com/_RcW8NBFDyc",
    },
    {
        id: 2,
        title: "Smart Watch",
        desc: "Stay connected and on top of your fitness goals with this sleek smartwatch. It tracks your steps, heart rate, and more, and syncs seamlessly with your phone.",
        price: 89.99,
        stock: 30,
        img: "https://source.unsplash.com/vvjU6nFNg6Q",
    },
    {
        id: 3,
        title: "Wireless Charger",
        desc: "Charge your phone quickly and conveniently with this wireless charger. Its compact design makes it easy to take with you on-the-go.",
        price: 29.99,
        stock: 100,
        img: "https://source.unsplash.com/hNfVOYz8sDw",
    },
    {
        id: 4,
        title: "Waterproof Phone Case",
        desc: "Protect your phone from water damage with this durable waterproof phone case. Its clear design lets you show off your phone's sleek design.",
        price: 19.99,
        stock: 75,
        img: "https://source.unsplash.com/8PnKjENRJ_o",
    },
    {
        id: 5,
        title: "Gaming Mouse",
        desc: "Take your gaming to the next level with this high-performance gaming mouse. Its ergonomic design and customizable buttons give you the edge you need to win.",
        price: 39.99,
        stock: 50,
        img: "https://source.unsplash.com/8_1F4R4-Sk4",
    },
    {
        id: 6,
        title: "Fitness Tracker",
        desc: "Stay motivated and track your fitness goals with this stylish fitness tracker. It monitors your heart rate, steps, and more, and provides real-time feedback to help you stay on track.",
        price: 69.99,
        stock: 40,
        img: "https://source.unsplash.com/XU0kOXoqtaM",
    },
    {
        id: 7,
        title: "Noise Cancelling Headphones",
        desc: "Enjoy your music or podcasts in peace with these noise-cancelling headphones. They offer crystal-clear sound quality and a comfortable fit for hours of use.",
        price: 129.99,
        stock: 20,
        img: "https://source.unsplash.com/XHSvYdLZs_A",
    },
    {
        id: 8,
        title: "Wireless Keyboard",
        desc: "Stay productive and comfortable with this wireless keyboard. Its ergonomic design and responsive keys make typing a breeze, and it connects easily to your computer or tablet.",
        price: 49.99,
        stock: 60,
        img: "https://source.unsplash.com/1LkF11nNcVg",
    },
    {
        id: 9,
        title: "Smart Thermostat",
        desc: "Control your home's temperature and save money on energy bills with this smart thermostat. It learns your schedule and adjusts the temperature accordingly.",
        price: 129.99,
        stock: 10,
        img: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    },
    {
        id: 10,
        title: "Portable Bluetooth Speaker",
        desc: "Take your music with you wherever you go with this portable Bluetooth speaker. Its compact size and long battery life make it perfect for outdoor activities.",
        price: 39.99,
        stock: 80,
        img: "https://source.unsplash.com/8EzgV7Qfxvg",
    },
    {
        id: 11,
        title: "Universal Phone Mount",
        desc: "Keep your phone secure and within reach while you drive with this universal phone mount. It easily attaches to your car's dashboard or windshield and can accommodate phones of various sizes.",
        price: 14.99,
        stock: 100,
        img: "https://source.unsplash.com/vlPa7oGwW8w",
    },
    {
        id: 12,
        title: "Electric Toothbrush",
        desc: "Achieve a brighter, healthier smile with this high-tech electric toothbrush. It comes with multiple brush heads and offers different modes for a personalized cleaning experience.",
        price: 59.99,
        stock: 50,
        img: "https://source.unsplash.com/L5fGsFYhPzY",
    },
    {
        id: 13,
        title: "Sleep Headphones",
        desc: "Fall asleep to your favorite sounds with these comfortable sleep headphones. The flat speakers fit snugly over your ears and won't interfere with your sleep.",
        price: 19.99,
        stock: 60,
        img: "https://source.unsplash.com/L8zTQQmLrN0",
    },
    {
        id: 14,
        title: "Power Bank",
        desc: "Never run out of battery again with this powerful and portable power bank. It can charge your phone multiple times and fits easily into your pocket or bag.",
        price: 24.99,
        stock: 100,
        img: "https://source.unsplash.com/60u6HkEXZME",
    },
    {
        id: 15,
        title: "Video Doorbell",
        desc: "Keep an eye on your home and stay secure with this advanced video doorbell. It sends alerts to your phone and lets you see and talk to visitors from anywhere.",
        price: 129.99,
        stock: 30,
        img: "https://source.unsplash.com/w7VmrkT2mK0",
    },
    {
        id: 16,
        title: "Smart Scale",
        desc: "Track your weight, body fat, and more with this high-tech smart scale. It syncs with your phone and offers personalized insights and recommendations.",
        price: 79.99,
        stock: 40,
        img: "https://source.unsplash.com/tjJ55a1x2-E",
    },
    {
        id: 17,
        title: "Robot Vacuum",
        desc: "Clean your floors effortlessly with this smart robot vacuum. It navigates around your home and can be controlled with your phone or voice commands.",
        price: 249.99,
        stock: 20,
        img: "https://source.unsplash.com/QJwtxOGfzXM",
    },
    {
        id: 18,
        title: "Wireless Headphones",
        desc: "Enjoy your music on-the-go with these sleek wireless headphones. They offer high-quality sound and a comfortable fit for hours of use.",
        price: 89.99,
        stock: 50,
        img: "https://source.unsplash.com/lWRX6GdJxuo",
    },
    {
        id: 19,
        title: "Indoor Security Camera",
        desc: "Keep an eye on your home while you're away with this indoor security camera. It has night vision and motion detection capabilities.",
        price: 89.99,
        stock: 15,
        img: "https://images.unsplash.com/photo-1571064617709-9bafb1e52fe5",
    },
    {
        id: 20,
        title: "Electric Kettle",
        desc: "Boil water quickly and easily with this electric kettle. It has a large capacity and automatic shut-off feature for added safety.",
        price: 29.99,
        stock: 25,
        img: "https://images.unsplash.com/photo-1551797767-8f8e94dfaeb7",
    },
    {
        id: 21,
        title: "Wireless Charging Pad",
        desc: "Charge your phone wirelessly with this sleek and stylish charging pad. It works with all Qi-compatible devices.",
        price: 19.99,
        stock: 30,
        img: "https://images.unsplash.com/photo-1608217969708-c33b56e27636",
    },
    {
        id: 22,
        title: "Smart Doorbell",
        desc: "See who's at your door from anywhere with this smart doorbell. It has a built-in camera and microphone for two-way communication.",
        price: 149.99,
        stock: 5,
        img: "https://images.unsplash.com/photo-1594805273327-733890914e9e",
    },
];

export default items;
